RejestrZaginionych/Models/MissingPerson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;

namespace RejestrZaginionych.Models {
    public class MissingPerson {
        
        [Key]
        public int Id { get; set; }
        [Required]
        [Display(Name = "Imię")]
        public String Name { get; set; }
        [Required]
        [Display(Name = "Wiek")]
        public int Age { get; set; }
        [Required]
        [Display(Name = "Kolor oczu")]
        public String EyeColor { get; set; }
        [Required]
        [Display(Name = "Kolor włosów")]
        public String HairColor { get; set; }
        [Required]
        [Display(Name = "Wzrost")]
        public String Height { get; set; }
        [Required]
        [Display(Name = "Data zaginięcia")]
        public String MissingDate { get; set; }
        [Display(Name = "Znaki szczególne")]
        public String DistinguishingMarks { get; set; }
        [Required]
        [Display(Name = "Miasto")]
        public String City { get; set; }
        [Display(Name = "Opis")]
        public String Description { get; set; }
        public int AddedByUserId { get; set; }

        [Display(Name = "Zdjęcie")]
        public string ImagePath { get; set; }

        [NotMapped]
        [Required]

        public HttpPostedFileBase ImageFile { get; set; }
    

    public virtual List<MissingPerson> MissingPersons { get; set; }


        public static List<MissingPerson> getList() {
            MissingPersonListContext db = new MissingPersonListContext();
            List<MissingPerson> MissingPersonList = db.MissingPersons.ToList();

            return MissingPersonList;
        }

        public void addMissingPerson() {

            MissingPersonListContext db = new MissingPersonListContext();

            db.MissingPersons.Add(this);
            db.SaveChanges();
        }

        public static MissingPerson getPopUpInfo(int userId) {
            MissingPerson person;

            MissingPersonListContext db = new MissingPersonListContext();
            try {
                person = db.MissingPersons.Single(u => u.Id == userId);
            }
            catch (InvalidOperationException e) {
                return null;
            }

            return person;
        } 

    }

}

RejestrZaginionych/Controllers/MissingPersonController.cs
using RejestrZaginionych.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RejestrZaginionych.Controllers
{
    public class MissingPersonController : Controller
    {
        // GET: MissingPerson
        public ActionResult Index() {
            ViewBag.MissingPersonList = Models.MissingPerson.getList();

            return View("MissingPersonList");
        }

        public ActionResult AddMissingPerson() {
            return View();
        }

        [HttpPost]
        public ActionResult AddMissingPerson([Bind(Exclude = "ImagePath")]MissingPerson missingPerson) {
            if (ModelState.IsValid == true) { 
                string FileName = Path.GetFileNameWithoutExtension(missingPerson.ImageFile.FileName);
                string FileExtension = Path.GetExtension(missingPerson.ImageFile.FileName);
                FileName = Guid.NewGuid().ToString() + FileExtension;
                string UploadPath = ConfigurationManager.AppSettings["UserImagePath"].ToString();
                missingPerson.ImagePath = UploadPath + FileName;
                missingPerson.ImageFile.SaveAs(Server.MapPath(missingPerson.ImagePath));

                User user = (User) Session["User"];
                missingPerson.AddedByUserId = user.Id;
                missingPerson.addMissingPerson();
                Debug.WriteLine("DZIALA");

                ViewBag.MissingPersonList = Models.MissingPerson.getList();

                return View("MissingPersonList");
            }
            else
                return View();
        }

        [HttpPost]
        public ActionResult GetPopUpData(int personId) {
            MissingPerson person = MissingPerson.getPopUpInfo(personId);
            return Json(person);
        }
    }
}

RejestrZaginionych/Views/MissingPerson/AddMissingPerson.cshtml
@model RejestrZaginionych.Models.MissingPerson

@{
    ViewBag.Title = "Dodawanie osoby zaginionej";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h3>Dodaj osobę poszukiwaną</h3>
<hr />
@using (Html.BeginForm("AddMissingPerson", "MissingPerson", FormMethod.Post, new {
    enctype = "multipart/form-data"
})) {
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Imię
        </div>
        <div style="width:70%">
            @Html.TextBoxFor(m => m.Name)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Wiek
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.Age)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.Age, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Data zaginięcia
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.MissingDate)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.MissingDate, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Kolor oczu
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.EyeColor)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.EyeColor, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Kolor włosów
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.HairColor)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.HairColor, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Wzrost
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.Height)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.Height, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Znaki szczególne
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.DistinguishingMarks)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.DistinguishingMarks, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Miasto
        </div>
        <div style="width:70%">
            @Html.EditorFor(m => m.City)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.City, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Opis
        </div>
        <div style="width:70%">
            @Html.TextAreaFor(m => m.Description)
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div style="display: flex" class="row">
        <div style="width:30%" class="form-label">
            Zdjęcie
        </div>
        <div style="width:70%">
            <input type="file" name="ImageFile" required />
            <div style="width: 100%">
                @Html.ValidationMessageFor(m => m.ImageFile, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>





    <input style="width: 440px; margin-top: 20px; max-width: 100%;" class="btn-primary" type="submit" value="Dodaj wpis" />
}

RejestrZaginionych/Views/MissingPerson/MissingPersonList.cshtml
@{
    ViewBag.Title = "Rejestr osób zaginionych";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="~/Scripts/MissingPersonList.js"></script>
<h3>@ViewBag.Title</h3>
<hr />
@if (Session["User"] == null) {
    <strong><span>By dodać zaginioną osobę należy się zalogować</span></strong>
}
else {
    <span><strong>@Html.ActionLink("Dodaj nowy wpis", "AddMissingPerson", "MissingPerson")</strong></span>
}

<table id="MissingPersonList" class="display" style="width: 100%">
    <thead>
        <tr>
            <th>Imię</th>
            <th>Wiek</th>
            <th>Kolor oczów</th>
            <th>Kolor włosów</th>
            <th>Wzrost</th>
            <th>Data zaginięcia</th>
            <th>Miasto</th>

        </tr>
    </thead>
    <tbody>
        @foreach (RejestrZaginionych.Models.MissingPerson person in ViewBag.MissingPersonList) {
            <tr class="missingPersonRow" data-person-id="@person.Id">
                <td>@person.Name</td>
                <td>@person.Age</td>
                <td>@person.EyeColor</td>
                <td>@person.HairColor</td>
                <td>@person.Height</td>
                <td>@person.MissingDate</td>
                <td>@person.City</td>

            </tr>

        }


    </tbody>
</table>